export enum LEAD_PROBABILITY {
  LOW = "LOW",
  MEDIUM = "MEDIUM",
  HIGH = "HIGH",
}

export enum CAMPAIGN_STEP {
  TARGET = "TARGET",
  LEADS = "LEADS",
  EMAILS = "EMAILS",
}

export enum CAMPAIGN_STATUS {
  DRAFT = "DRAFT",
  ACTIVE = "ACTIVE",
  IN_PROCESS = "IN_PROCESS",
  COMPLETED = "COMPLETED",
}

export enum COMPANY_SIZE {
  "1-10" = "1-10",
  "11-50" = "11-50",
  "51-200" = "51-200",
  "201-500" = "201-500",
  "501-1000" = "501-1000",
  "1001-5000" = "1001-5000",
  "5001-10000" = "5001-10000",
  "10001+" = "10001+",
}

export enum REVENUE_STAGES {
  "$0-$1m" = "$0-$1m",
  "$1m-$10m" = "$1m-$10m",
  "$10m-$25m" = "$10m-$25m",
  "$25m-$50m" = "$25m-$50m",
  "$50m-$100m" = "$50m-$100m",
  "$100m-$250m" = "$100m-$250m",
  "$250m-$500m" = "$250m-$500m",
  "$500m-$1b" = "$500m-$1b",
  "$1b-$10b" = "$1b-$10b",
  "$10b+" = "$10b+",
}

export const INDUSTRIES = [
  "accounting",
  "airlines/aviation",
  "alternative dispute resolution",
  "alternative medicine",
  "automotive",
  "aviation & aerospace",
  "computer & network security",
  "computer games",
  "computer hardware",
  "computer networking",
  "computer software",
  "executive office",
  "facilities services",
  "farming",
  "financial services",
  "fine art",
  "fishery",
  "food & beverages",
  "food production",
  "fund-raising",
  "furniture",
  "hospitality",
  "human resources",
  "international trade and development",
  "internet",
  "market research",
  "marketing and advertising",
  "mechanical or industrial engineering",
  "media production",
  "plastics",
  "political organization",
  "primary/secondary education",
  "printing",
  "professional training & coaching",
  "ranching",
  "real estate",
  "utilities",
  "venture capital & private equity",
  "warehousing",
  "wholesale",
];

export const LOCATIONS = [
  "canada",
  "greece",
  "greenland",
  "grenada",
  "india",
  "indonesia",
  "iran",
  "iraq",
  "kyrgyzstan",
  "laos",
  "latvia",
  "mexico",
  "new zealand",
  "nicaragua",
  "niger",
  "nigeria",
  "pakistan",
  "russia",
  "united arab emirates",
  "united kingdom",
  "united states",
  "yemen",
  "zimbabwe",
];
